import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fb',
    },
    headerWrapper: {
        backgroundColor: '#2A5C8D',
        paddingHorizontal: 20,
        paddingTop: 50,
        paddingBottom: 70,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    bottomContainer: {
        flex: 1,
        marginTop: -20,
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 16,
    },
    header: {
        fontSize: 20,
        fontWeight: '600',
        color: 'white',
        alignItems: 'center',
        flexDirection: 'row',
        fontFamily: 'Poppins-SemiBold',
    },
    notificationWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        borderRadius: 15,
        backgroundColor: "#ccc",
        justifyContent: "space-around",
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 16,
        marginVertical: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    titleText: {
        fontSize: 15,
        fontWeight: '600',
        marginBottom: 6,
        color: '#1a1a1a',
        fontFamily: 'Poppins-SemiBold',
    },
    sigText: {
        fontSize: 14,
        color: '#444',
        marginBottom: 4,
        fontFamily: 'Poppins-Regular',
    },
    dateText: {
        fontSize: 13,
        color: '#888',
        marginBottom: 14,
        fontFamily: 'Poppins-Regular',
    },
    refillButton: {
        backgroundColor: '#1F5FA1',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
    },
    refillButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 15,
        fontFamily: 'Poppins-SemiBold',
    },
    emptyText: {
        textAlign: 'center',
        marginTop: 40,
        fontSize: 16,
        color: '#999',
        fontFamily: 'Poppins-Regular',
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '85%',
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
    },
    label: {
        fontWeight: '600',
        fontSize: 14,
        color: '#333',
        marginTop: 10,
        fontFamily: 'Poppins-SemiBold',
    },
    value: {
        fontSize: 14,
        color: '#444',
        marginTop: 4,
        fontFamily: 'Poppins-Regular',
    },
});

export default styles;
