import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  gradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 50,
  },
  headerText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#ffffff',
    flex: 1,
    textAlign: 'center',
    marginTop: 30,
    fontFamily: 'Poppins-SemiBold',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#dce3f0',
    borderRadius: 12,
    marginBottom: 30,
    marginHorizontal: 20,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: '#1e3a8a',
    borderRadius: 12,
  },
  tabText: {
    fontSize: 16,
    color: '#555',
    fontFamily: 'Poppins-Regular',
  },
  activeTabText: {
    color: '#fff',
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
  },
  deviceContainer: {
    alignItems: 'center',
    marginBottom: 60,
  },
  deviceBox: {
    width: 280,
    backgroundColor: '#F7F7F7',
    borderRadius: 18,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    padding: 30,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  screen: {
    width: 220,
    minHeight: 220,
    backgroundColor: '#121212',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    padding: 10,
  },
  readingScreen: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  readingTitle: {
    color: '#ffffff', 
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 8,
    fontFamily: 'Poppins-Bold',
  },
  readingValue: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Bold',
  },
  readingLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#ffffff',
    marginTop: 16,
    fontFamily: 'Poppins-Medium',
  },
  bottomContainerLight: {
    width: '100%',
    height: 40,
    backgroundColor: '#EEE',
    borderRadius: 10,
    marginTop: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  refreshButton: {
    alignSelf: 'center',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 12,
  },
  card: {
    backgroundColor: '#f0f4f8',
    borderRadius: 12,
    padding: 10,
    marginVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    width: 200,
  },
  spo2Card: {
    backgroundColor: '#e0f7ff',
  },
  iconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardContent: {
    marginLeft: 10,
  },
  cardTitle: {
    fontSize: 16,
    color: '#1e3a8a',
    fontFamily: 'Poppins-Regular',
  },
  cardValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1e3a8a',
    fontFamily: 'Poppins-Bold',
  },
  glucoseContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  glucoseTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
    fontFamily: 'Poppins-SemiBold',
  },
  glucoseValue: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#ffffff',
    marginVertical: 8,
    fontFamily: 'Poppins-Bold',
  },
  legendContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 10,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  backButton: {
    marginLeft: 10, 
  },
  legendDot: {
    width: 18,
    height: 6,
    borderRadius: 5,
    marginRight: 6,
  },
  legendText: {
    fontSize: 14,
    color: '#1e3a8a',
    fontFamily: 'Poppins-Regular',
  },
  footer: {
    alignItems: 'center',
    marginTop:20,
  },
  footerTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1e3a8a',
    fontFamily: 'Poppins-Bold',
  },
  footerSub: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1e3a8a',
    textAlign: 'center',
    marginTop: 10,
    padding:5,
    fontFamily: 'Poppins-Medium',
  },
});

export default styles;
